name: CI

on: [push]

jobs:
  #simple-build:
  #  runs-on: ${{ matrix.os }}
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      os: [ubuntu-latest, macos-latest, windows-latest]
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Report environment
  #    run: env | sort
  #  - name: Run CMake
  #    uses: lukka/run-cmake@v0.5
  #    with:
  #      buildWithCMake: false
  
  cvmfs-native:
    runs-on: [ubuntu-latest]
    steps:
      - name: Start CVMFS
        run: | 
          sudo apt-get install lsb-release
          wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
          sudo dpkg -i cvmfs-release-latest_all.deb
          rm -f cvmfs-release-latest_all.deb
          sudo apt-get update
          sudo apt-get install cvmfs cvmfs-config-default
          sudo cvmfs_config setup
          echo  "CVMFS_REPOSITORIES=sft.cern.ch" | sudo tee -a  /etc/cvmfs/default.local > /dev/null
          echo  "CVMFS_HTTP_PROXY=DIRECT"  | sudo tee -a  /etc/cvmfs/default.local > /dev/null
          sudo service autofs restart
          sudo cvmfs_config probe
      - name: Pull Docker Imake
        run: docker pull centos:7
      - name: Create Docker Container
        run: docker run -itd --name builder -v $GITHUB_WORKSPACE:/workspace -v /cvmfs:/cvmfs -w /workspace centos:7
      - uses: actions/checkout@v2
      - name: Docker Exec Test
        run: |
          docker exec builder bash -c '. /cvmfs/sft.cern.ch/lcg/views/LCG_96bpython3/x86_64-centos7-gcc8-opt/setup.sh && gcc --version'
          docker exec builder bash -c 'ls -larth .'
