name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      uses: lukka/run-cmake@v0.5
      with:
        buildWithCMake: false
