name: CI

on: [push]

jobs:
  #simple-build:
  #  runs-on: ${{ matrix.os }}
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      os: [ubuntu-latest, macos-latest, windows-latest]
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Report environment
  #    run: env | sort
  #  - name: Run CMake
  #    uses: lukka/run-cmake@v0.5
  #    with:
  #      buildWithCMake: false
  
  cvmfs-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Start CVMFS
        run: | 
          sudo apt-get install lsb-release
          wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
          sudo dpkg -i cvmfs-release-latest_all.deb
          rm -f cvmfs-release-latest_all.deb
          sudo apt-get update
          sudo apt-get install cvmfs cvmfs-config-default
          sudo cvmfs_config setup
          echo  "CVMFS_REPOSITORIES=sft.cern.ch" | sudo tee -a  /etc/cvmfs/default.local > /dev/null
          echo  "CVMFS_HTTP_PROXY=DIRECT"  | sudo tee -a  /etc/cvmfs/default.local > /dev/null
          sudo service autofs restart
          sudo cvmfs_config probe
      - name: Load LCG
        run: |
          . /cvmfs/sft.cern.ch/lcg/views/LCG_96bpython3/x86_64-ubuntu1804-gcc8-opt/setup.sh
          env | sort
      - name: Check LCG env
        run: env | sort
        
